### Register Admin
POST https://novianirwana-production.up.railway.app/auth/register/admin
Content-Type: application/json

{
  "name": "Admin Name",
  "email": "admin@example.com",
  "password": "adminpassword"
}






















### Register Consumer
POST https://novianirwana-production.up.railway.app/auth/register/consumer
Content-Type: application/json

{
  "name": "novia nirwana",
  "email": "novianirwana@example.com",
  "password": "consumerpassword"
}




















###

### Register Seller
POST https://novianirwana-production.up.railway.app/auth/register/seller
Content-Type: application/json

{
  "name": "Seller Name",
  "email": "seller@example.com",
  "password": "sellerpassword"
}

###

### Login Admin
POST https://novianirwana-production.up.railway.app/auth/login/admin
Content-Type: application/json

{
  "email": "ddd@example.com",
  "password": "adminpassword"
}

###

### Login Consumer
POST https://novianirwana-production.up.railway.app/auth/login/consumer
Content-Type: application/json

{
  "email": "consumer@example.com",
  "password": "consumerpassword"
}

###

### Login Seller
POST https://novianirwana-production.up.railway.app/auth/login/seller
Content-Type: application/json

{
  "email": "seller@example.com",
  "password": "sellerpassword"
}









### Tambahkan sepatu baru HARUS AKSES SELLER
POST https://novianirwana-production.up.railway.app/seller/shoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlbGxlckBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTcwMzkwMSwiZXhwIjoxNzIxNzA3NTAxfQ.WI_Dpk-uTTYqc2al3C_qoLZh81yySYvQX_oCgwK3ZGU

{
  "name": "NIKE JORDAN",
  "description": "Newest model of Air Max",
  "price": 150,
  "SellerId": 1,
  "size": 42,
  "stock": 10,
  "imageUrl": "http://example.com/image.jpg"
}








###

### Perbarui stok sepatu HARUS AKSES SELLER
PUT https://novianirwana-production.up.railway.app/seller/shoes/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlbGxlckBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTM1ODcxOSwiZXhwIjoxNzIxMzYyMzE5fQ.Kf65Ped_jey3nKUuqUA-lu1COYUDHwGLpmocs1Go24c

{
  "stock": 50
}

###


### Dapatkan daftar sepatu
GET https://novianirwana-production.up.railway.app/consumer/shoes
Content-Type: application/json

###

### Dapatkan detail sepatu
GET https://novianirwana-production.up.railway.app/consumer/shoes/3
Content-Type: application/json

###

### Buat pembayaran baru
POST https://novianirwana-production.up.railway.app/consumer/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbnN1bWVyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxMzU5MTc0LCJleHAiOjE3MjEzNjI3NzR9.0T42cAs0Xh2fnPOy9HCPFQF_KkbmamTWnvwR8oWb3fw

{
  "ConsumerId": 1,
  "shoes": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 2,
      "quantity": 1
    }
  ],
  "totalAmount": 300,
  "paymentMethod": "Tunai",
  "status":"Completed"
}

### Get Sales Report
GET https://novianirwana-production.up.railway.app/admin/sales-report
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRkZEBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTM5MzE4OSwiZXhwIjoxNzIxMzk2Nzg5fQ.dnIJ20fp6Bz15t0QnvYXAEPOLwrqjIpPrY9LcPPjvFU

### Get Stock Status
GET https://novianirwana-production.up.railway.app/admin/stock-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRkZEBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTM5MzE4OSwiZXhwIjoxNzIxMzk2Nzg5fQ.dnIJ20fp6Bz15t0QnvYXAEPOLwrqjIpPrY9LcPPjvFU

